// <auto-generated />
using Connectied.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectied.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Connectied.Domain.GuestLists.GuestList", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Event1Attend")
                        .HasColumnType("int");

                    b.Property<int>("Event1Quota")
                        .HasColumnType("int");

                    b.Property<int>("Event1Rsvp")
                        .HasColumnType("int");

                    b.Property<int>("Event2AngpaoCount")
                        .HasColumnType("int");

                    b.Property<int>("Event2Attend")
                        .HasColumnType("int");

                    b.Property<int>("Event2GiftCount")
                        .HasColumnType("int");

                    b.Property<int>("Event2Quota")
                        .HasColumnType("int");

                    b.Property<int>("Event2Rsvp")
                        .HasColumnType("int");

                    b.Property<int>("Event2Souvenir")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GuestLists");
                });
#pragma warning restore 612, 618
        }
    }
}
